// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portfolio.Infrastructure.Data.Sql.Context;

#nullable disable

namespace Portfolio.Infrastructure.Data.Sql.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20230801002335_CreateTablePortfolio")]
    partial class CreateTablePortfolio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("aspnetroles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "bc2d399b-281d-4199-878e-2495733d616a",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "415577a4-adea-479e-ae3d-31ca1a8cd5ab",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnetrole_claims", (string)null);
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValue(new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(6627))
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("character varying(125)")
                        .HasColumnName("name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("character varying(125)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValue(new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(6788))
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("aspnetusers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bf8fa88c-57c2-4345-8b4e-d961d48a610e",
                            CreatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 163, DateTimeKind.Local).AddTicks(867),
                            Email = "andre_luiz.b5@outlook.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "ALB Portfolio",
                            LockoutEnabled = false,
                            NormalizedEmail = "ANDRE_LUIZ.B5@OUTLOOK.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEPWFgJ33MVw+m7YmiiYZzntKKHWgJt78bjcQ9jOzJg82Z6nvShTE7GHhZBa9IBXLxw==",
                            PhoneNumber = "31 995600166",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "92fbe55b-dfc5-4cc6-af1d-10f74832db85",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 163, DateTimeKind.Local).AddTicks(878),
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("aspnetuser_claims", (string)null);
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("aspnetuser_logins", (string)null);
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnetuser_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetUserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("aspnetuser_tokens", (string)null);
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Sql.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValue(new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(7201))
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Extra")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("extra");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValue(new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(7300))
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("configuration");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5873),
                            Token = "EMAIL_LOGIN",
                            UpdatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5878),
                            Value = "todo"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5880),
                            Token = "EMAIL_PASSWORD",
                            UpdatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5881),
                            Value = "todo"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5882),
                            Token = "EMAIL_PORT",
                            UpdatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5882),
                            Value = "todo"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5883),
                            Token = "EMAIL_SMTP",
                            UpdatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5883),
                            Value = "todo"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5884),
                            Token = "ATTEMPTS_LOGIN_ERROR",
                            UpdatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5884),
                            Value = "todo"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5885),
                            Token = "ATTEMPTS_LOGIN_ERROR_DAYS_BLOCK",
                            UpdatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5885),
                            Value = "todo"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5886),
                            Token = "MINUTES_EXPIRES_ACCESS_TOKEN",
                            UpdatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5886),
                            Value = "todo"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5887),
                            Token = "MINUTES_EXPIRES_REFRESH_TOKEN",
                            UpdatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5887),
                            Value = "todo"
                        });
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Sql.GenericType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValue(new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(7712))
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValue(new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(7827))
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("value");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("boolean")
                        .HasColumnName("value_bool");

                    b.HasKey("Id");

                    b.ToTable("generic_type");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5942),
                            Description = "Status de jornada experiência de trabalho",
                            Token = "EXPERIENCE_WORK_STATUS",
                            UpdatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5943),
                            Value = "Integral"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5944),
                            Description = "Status de jornada experiência de trabalho",
                            Token = "EXPERIENCE_WORK_STATUS",
                            UpdatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5945),
                            Value = "Meio período"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5946),
                            Description = "Status de jornada experiência de trabalho",
                            Token = "EXPERIENCE_WORK_STATUS",
                            UpdatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5946),
                            Value = "Noturna"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5947),
                            Description = "Status de jornada experiência de trabalho",
                            Token = "EXPERIENCE_WORK_STATUS",
                            UpdatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5947),
                            Value = "Turno"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5948),
                            Description = "Status de faculdade/curso experiência de trabalho",
                            Token = "EDUCATION_STATUS",
                            UpdatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5948),
                            Value = "Em curso"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5949),
                            Description = "Status de faculdade/curso experiência de trabalho",
                            Token = "EDUCATION_STATUS",
                            UpdatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5949),
                            Value = "Concluído"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5950),
                            Description = "Status de faculdade/curso experiência de trabalho",
                            Token = "EDUCATION_STATUS",
                            UpdatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5950),
                            Value = "Incompleto"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5951),
                            Description = "Status de faculdade/curso experiência de trabalho",
                            Token = "EDUCATION_STATUS",
                            UpdatedAt = new DateTime(2023, 7, 31, 21, 23, 35, 164, DateTimeKind.Local).AddTicks(5951),
                            Value = "Trancado"
                        });
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Sql.PortfolioConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutMe")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("about_me");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValue(new DateTime(2023, 7, 31, 21, 23, 35, 165, DateTimeKind.Local).AddTicks(2339))
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("firstname");

                    b.Property<string>("GithubLink")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("github_link");

                    b.Property<string>("KeyAccess")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("key_access");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("lastname");

                    b.Property<string>("LinkedinLink")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("linkedin_link");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValue(new DateTime(2023, 7, 31, 21, 23, 35, 165, DateTimeKind.Local).AddTicks(2460))
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("portfolio");
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Sql.PortfolioConfigUsersAssociate", b =>
                {
                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer")
                        .HasColumnName("portfolio_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("PortfolioId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("portfolio_users");
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetRoleClaim", b =>
                {
                    b.HasOne("Portfolio.Core.Entities.Identity.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetUserClaim", b =>
                {
                    b.HasOne("Portfolio.Core.Entities.Identity.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetUserLogin", b =>
                {
                    b.HasOne("Portfolio.Core.Entities.Identity.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetUserRole", b =>
                {
                    b.HasOne("Portfolio.Core.Entities.Identity.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Core.Entities.Identity.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetUserToken", b =>
                {
                    b.HasOne("Portfolio.Core.Entities.Identity.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Sql.PortfolioConfigUsersAssociate", b =>
                {
                    b.HasOne("Portfolio.Core.Entities.Sql.PortfolioConfig", "Portfolio")
                        .WithMany("PortolioUsersAssociates")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Portfolio.Core.Entities.Identity.AspNetUser", "User")
                        .WithMany("PortolioUsersAssociates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetUser", b =>
                {
                    b.Navigation("PortolioUsersAssociates");
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Sql.PortfolioConfig", b =>
                {
                    b.Navigation("PortolioUsersAssociates");
                });
#pragma warning restore 612, 618
        }
    }
}
