// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portfolio.Infrastructure.Data.Sql.Context;

#nullable disable

namespace Portfolio.Infrastructure.Data.Sql.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20230731220952_CreateTableGenericType")]
    partial class CreateTableGenericType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("aspnetroles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "3a2658a0-b474-462e-b86d-1b8613201d96",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "31aa1ce2-0175-4140-ba14-e2dd8d120dc9",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnetrole_claims", (string)null);
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValue(new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3824))
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("character varying(125)")
                        .HasColumnName("name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("character varying(125)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValue(new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3965))
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("aspnetusers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "92cee91a-789d-4cbf-8277-e4db49bf9f2e",
                            CreatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 849, DateTimeKind.Local).AddTicks(9407),
                            Email = "andre_luiz.b5@outlook.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "ALB Portfolio",
                            LockoutEnabled = false,
                            NormalizedEmail = "ANDRE_LUIZ.B5@OUTLOOK.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEB+zHxBGwA377IQcwq+n4kDm1K7sqvkqo7i0JodCmWhKe3iS0WLXhv4xa8P/abSA3Q==",
                            PhoneNumber = "31 995600166",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a00e90c6-fd99-48c2-b1bc-98ddccb1b448",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 849, DateTimeKind.Local).AddTicks(9417),
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("aspnetuser_claims", (string)null);
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("aspnetuser_logins", (string)null);
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnetuser_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetUserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("aspnetuser_tokens", (string)null);
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Sql.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValue(new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(4335))
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Extra")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("extra");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValue(new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(4439))
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("configuration");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3162),
                            Token = "EMAIL_LOGIN",
                            UpdatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3163),
                            Value = "todo"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3166),
                            Token = "EMAIL_PASSWORD",
                            UpdatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3166),
                            Value = "todo"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3167),
                            Token = "EMAIL_PORT",
                            UpdatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3167),
                            Value = "todo"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3168),
                            Token = "EMAIL_SMTP",
                            UpdatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3168),
                            Value = "todo"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3169),
                            Token = "ATTEMPTS_LOGIN_ERROR",
                            UpdatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3169),
                            Value = "todo"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3170),
                            Token = "ATTEMPTS_LOGIN_ERROR_DAYS_BLOCK",
                            UpdatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3170),
                            Value = "todo"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3171),
                            Token = "MINUTES_EXPIRES_ACCESS_TOKEN",
                            UpdatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3171),
                            Value = "todo"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3172),
                            Token = "MINUTES_EXPIRES_REFRESH_TOKEN",
                            UpdatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3172),
                            Value = "todo"
                        });
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Sql.GenericType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValue(new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(4865))
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValue(new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(4965))
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("value");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("boolean")
                        .HasColumnName("value_bool");

                    b.HasKey("Id");

                    b.ToTable("generic_type");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3247),
                            Description = "Status de jornada experiência de trabalho",
                            Token = "EXPERIENCE_WORK_STATUS",
                            UpdatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3247),
                            Value = "Integral"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3249),
                            Description = "Status de jornada experiência de trabalho",
                            Token = "EXPERIENCE_WORK_STATUS",
                            UpdatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3250),
                            Value = "Meio período"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3250),
                            Description = "Status de jornada experiência de trabalho",
                            Token = "EXPERIENCE_WORK_STATUS",
                            UpdatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3251),
                            Value = "Noturna"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3251),
                            Description = "Status de jornada experiência de trabalho",
                            Token = "EXPERIENCE_WORK_STATUS",
                            UpdatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3252),
                            Value = "Turno"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3252),
                            Description = "Status de faculdade/curso experiência de trabalho",
                            Token = "EDUCATION_STATUS",
                            UpdatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3253),
                            Value = "Em curso"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3253),
                            Description = "Status de faculdade/curso experiência de trabalho",
                            Token = "EDUCATION_STATUS",
                            UpdatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3254),
                            Value = "Concluído"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3254),
                            Description = "Status de faculdade/curso experiência de trabalho",
                            Token = "EDUCATION_STATUS",
                            UpdatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3255),
                            Value = "Incompleto"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3255),
                            Description = "Status de faculdade/curso experiência de trabalho",
                            Token = "EDUCATION_STATUS",
                            UpdatedAt = new DateTime(2023, 7, 31, 19, 9, 51, 851, DateTimeKind.Local).AddTicks(3256),
                            Value = "Trancado"
                        });
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetRoleClaim", b =>
                {
                    b.HasOne("Portfolio.Core.Entities.Identity.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetUserClaim", b =>
                {
                    b.HasOne("Portfolio.Core.Entities.Identity.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetUserLogin", b =>
                {
                    b.HasOne("Portfolio.Core.Entities.Identity.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetUserRole", b =>
                {
                    b.HasOne("Portfolio.Core.Entities.Identity.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Core.Entities.Identity.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Identity.AspNetUserToken", b =>
                {
                    b.HasOne("Portfolio.Core.Entities.Identity.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
